export const CUSTOMER_ACTION_TYPES = {
  GET_ALL_CUSTOMERS_START: 'customer/GET_ALL_CUSTOMERS_START',
  GET_ALL_CUSTOMERS_SUCCESS: 'customer/GET_ALL_CUSTOMERS_SUCCESS',
  GET_ALL_CUSTOMERS_FAILED: 'customer/GET_ALL_CUSTOMERS_FAILED',

  GET_A_CUSTOMER_START: 'customer/GET_A_CUSTOMER_START',
  GET_A_CUSTOMER_SUCCESS: 'customer/GET_A_CUSTOMER_SUCCESS',
  GET_A_CUSTOMER_FAILED: 'customer/GET_A_CUSTOMER_FAILED',
}