export const SHIPMENT_ACTION_TYPES = {
  GET_ALL_SHIPMENTS_START: 'shipment/GET_ALL_SHIPMENTS_START',
  GET_ALL_SHIPMENTS_SUCCESS: 'shipment/GET_ALL_SHIPMENTS_SUCCESS',
  GET_ALL_SHIPMENTS_FAILED: 'shipment/GET_ALL_SHIPMENTS_FAILED',

  GET_A_SHIPMENT_START: 'shipment/GET_A_SHIPMENT_START',
  GET_A_SHIPMENT_SUCCESS: 'shipment/GET_A_SHIPMENT_SUCCESS',
  GET_A_SHIPMENT_FAILED: 'shipment/GET_A_SHIPMENT_FAILED',
}